version: 2.1

commands:
  runtests:
    steps:
      - checkout
      - run: pip install pyflakes==1.5.0
      - run: pyflakes libhoney && python setup.py test

executors:
  python2-7:
    docker:
      - image: circleci/python:2.7
  python3-5:
    docker:
      - image: circleci/python:3.5
  python3-6:
    docker:
      - image: circleci/python:3.6

jobs:
  test_python2-7:
    executor: python2-7
    steps:
      - runtests
  test_python3-5:
    executor: python3-5
    steps:
      - runtests
  test_python3-6:
    executor: python3-6
    steps:
      - runtests

workflows:
  version: 2
  build_libhoney:
    jobs:
      - test_python2-7
      - test_python3-5
      - test_python3-6